version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=default
  zap:
    image: owasp/zap2docker-stable
    command: tail -f /dev/null
    ports:
      - '8081:8080' # optional mapping for ZAP UI
